#!/usr/bin/env python3
"""
Firecrawl Blog to Markdown Converter
Converts blog posts and articles to clean markdown using Firecrawl SDK.
"""

import os
import click
import json
from dotenv import load_dotenv
from firecrawl import FirecrawlApp

load_dotenv()

def create_markdown_file(content: str, filename: str) -> str:
    """Create markdown file with proper formatting."""
    # Add header with metadata
    header = f"""# Blog Post Converted to Markdown

*Generated by Firecrawl Blog Converter*
*URL: {filename}*

---

"""
    return header + content

@click.command()
@click.option('--url', '-u', required=True, help='URL of the blog post to convert')
@click.option('--output', '-o', default='output', help='Output directory')
@click.option('--format', '-f', type=click.Choice(['markdown', 'text']), default='markdown', help='Output format')
@click.option('--scrape-options', '-s', help='Scrape options as JSON string')
def convert_blog(url: str, output: str, format: str, scrape_options: str):
    """Convert a blog post URL to clean markdown using Firecrawl."""
    
    try:
        # Initialize Firecrawl client
        api_key = os.getenv('FIRECRAWL_API_KEY')
        if not api_key:
            click.echo("Error: FIRECRAWL_API_KEY environment variable not set", err=True)
            return
        
        client = FirecrawlApp(api_key=api_key)
        
        # Parse scrape options if provided
        options = {}
        if scrape_options:
            try:
                options = json.loads(scrape_options)
            except json.JSONDecodeError:
                click.echo("Error: Invalid JSON in scrape options", err=True)
                return
        
        click.echo(f"Converting blog post: {url}")
        
        # Scrape the blog post
        result = client.scrape_url(url, options)
        
        if not result or 'markdown' not in result:
            click.echo("Error: Failed to scrape blog post", err=True)
            return
        
        # Create output directory if it doesn't exist
        os.makedirs(output, exist_ok=True)
        
        # Generate filename from URL
        from urllib.parse import urlparse
        parsed_url = urlparse(url)
        domain = parsed_url.netloc.replace('.', '_')
        path = parsed_url.path.replace('/', '_').strip('_')
        if not path:
            path = 'home'
        filename = f"{domain}_{path}.md"
        filepath = os.path.join(output, filename)
        
        # Create markdown content
        if format == 'markdown':
            content = create_markdown_file(result['markdown'], url)
        else:
            content = result.get('text', result.get('markdown', ''))
        
        # Save the file
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        click.echo(f"✅ Successfully converted blog post to: {filepath}")
        
        # Display some stats
        word_count = len(content.split())
        click.echo(f"📄 Word count: {word_count}")
        
        # Show first few lines as preview
        preview = '\n'.join(content.split('\n')[:10])
        click.echo(f"📖 Preview:")
        click.echo(preview)
        
    except Exception as e:
        click.echo(f"Error: {str(e)}", err=True)

if __name__ == '__main__':
    convert_blog()