#!/usr/bin/env python3
"""
Simple test script for the Firecrawl Blog Converter
"""

import unittest
import os
import sys
sys.path.append('.')

class TestBlogConverter(unittest.TestCase):
    """Test cases for the blog converter."""
    
    def test_import(self):
        """Test that the blog converter can be imported."""
        try:
            from blog_converter import convert_blog
            self.assertTrue(True)
        except ImportError as e:
            self.fail(f"Failed to import blog_converter: {e}")
    
    def test_create_markdown_file(self):
        """Test markdown file creation function."""
        try:
            from blog_converter import create_markdown_file
            
            test_content = "# Test Title\n\nThis is a test content."
            filename = "https://example.com/test"
            
            result = create_markdown_file(test_content, filename)
            
            self.assertIn("# Test Title", result)
            self.assertIn("Generated by Firecrawl Blog Converter", result)
            self.assertIn(filename, result)
            
        except Exception as e:
            self.fail(f"Markdown file creation failed: {e}")
    
    def test_requirements_file_exists(self):
        """Test that requirements.txt exists and has required packages."""
        self.assertTrue(os.path.exists('requirements.txt'))
        
        with open('requirements.txt', 'r') as f:
            content = f.read()
            
        self.assertIn('firecrawl', content)
        self.assertIn('requests', content)
    
    def test_readme_exists(self):
        """Test that README.md exists."""
        self.assertTrue(os.path.exists('README.md'))
        
        with open('README.md', 'r') as f:
            content = f.read()
            
        self.assertIn('Firecrawl Blog to Markdown Converter', content)
        self.assertIn('Installation', content)

def main():
    """Run the tests."""
    print("🧪 Running Blog Converter Tests...")
    print("=" * 40)
    
    # Run tests
    unittest.main(verbosity=2)

if __name__ == '__main__':
    main()